services:
  web:
    image: nginx:alpine
    container_name: motivation-web
    ports:
      - "8000:80"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:ro

  api:
    build: ./api
    container_name: motivation-api
    ports:
      - "5001:5001"

  admin:
    image: nginx:alpine
    container_name: motivation-admin